var course =[
    { "id":"1",
      "name":"2020 Complete Python Bootcamp: From Zero to Hero in Python",
      "amount":9.99,
      "img":"https://img-a.udemycdn.com/course/240x135/567828_67d0.jpg",
      "teacher":"Jose Portilla", 
    },
    { "id":"2",
      "name":"The Web Developer Bootcamp",
      "amount":8.99,
      "img":"https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
      "teacher":"Kirill Eremenko, Hadelin de Ponteves, SuperDataScience Team, SuperDataScience Support", 
    },
    { "id":"3",
      "name":"Machine Learning A-Z™: Hands-On Python & R In Data Science",
      "amount":78.90,
      "img":"https://img-a.udemycdn.com/course/240x135/950390_270f_3.jpg",
      "teacher":"Kirill Eremenko, Hadelin de Ponteves, SuperDataScience Team, SuperDataScience Support",  
    },
    { "id":"4",
      "name":"Angular - The Complete Guide (2020 Edition)",
      "amount":56.89,
      "img":"https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
      "teacher":"Maximilian Schwarzmüller",  
    },
    { "id":"5",
      "name":"Java Programming Masterclass for Software Developers",
      "amount":78.90,
      "img":"https://img-a.udemycdn.com/course/240x135/533682_c10c_4.jpg",
      "teacher":"Tim Buchalka, Tim Buchalka's Learn Programming Academy, Goran Lochert",  
    },
    { "id":"6",
      "name":"React - The Complete Guide (incl Hooks, React Router, Redux)",
      "amount":38.90,
      "img":"https://img-a.udemycdn.com/course/240x135/1362070_b9a1_2.jpg",
      "teacher":"Academind by Maximilian Schwarzmüller, Maximilian Schwarzmüller",  
    },
    { "id":"7",
      "name":"Python for Data Science and Machine Learning Bootcamp",
      "amount":67.90,
      "img":"https://img-a.udemycdn.com/course/240x135/903744_8eb2.jpg",
      "teacher":"Jose Portilla"  
    },
    { "id":"8",
      "name":"The Complete JavaScript Course 2020: Build Real Projects!",
      "amount":45.89,
      "img":"https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg",
      "teacher":"Jonas Schmedtmann"  
    },
    { "id":"9",
      "name":"The Complete 2020 Web Development Bootcamp",
      "amount":56.89,
      "img":"https://img-a.udemycdn.com/course/240x135/1565838_e54e_11.jpg",
      "teacher":"Dr. Angela Yu"  
    },
    { "id":"10",
      "name":"Complete C# Unity Game Developer 2D",
      "amount":78.45,
      "img":"https://img-a.udemycdn.com/course/240x135/258316_55e9_8.jpg",
      "teacher":"Ben Tristem, GameDev.tv Team, Rick Davidson",  
    },
    { "id":"11",
      "name":"The Data Science Course 2020: Complete Data Science Bootcamp",
      "amount":98.78,
      "img":"https://img-a.udemycdn.com/course/240x135/1754098_e0df_3.jpg",
      "teacher":"365 Careers, 365 Careers Team"  
    },
    { "id":"12",
      "name":"Modern React with Redux [2020 Update]",
      "amount":99.90,
      "img":"https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg",
      "teacher":"Stephen Grider"  
    }

];

export default course;